import type { Metadata } from 'next'
import './globals.css'
import { fontBody } from './font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`max-w-[1200px] mx-auto antialiased scroll-smooth${fontBody.className}`}
      >
        {children}
      </body>
    </html>
  )
}
